language: python
python:
  - "2.7"
install:
  - pip install pyyaml
script: 
  - python merge_logic.py testcases/test4/dir1/dir2/dir3/dir4/input.yaml
  #Testcases using python Unittest
  - python test_merge.py